import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import QueryClientProvider from "~/components/QueryClientProvider";
import Sidebar from "~/components/Sidebar";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="flex">
        <QueryClientProvider>
          <TRPCReactProvider>
            <Sidebar />
            {children}
          </TRPCReactProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
