name: Update PTCG API Data

on:
  # Runs everyday
  schedule:
    - cron: 0 0 * * *

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

concurrency:
  group: "ptcg-api"
  cancel-in-progress: true

jobs:
  # Update job
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Update Packages
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive
      - name: Commit update
        run: |
            git config --global user.name 'PTCG API Bot'
            git config --global user.email 'bot@noreply.github.com'
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
            git add -A
            git commit -am "chore: auto updated remote sources" && git push || echo "No changes to commit"
